### ISSUE TITLE
网址无法访问

### ISSUE THREAD

**Issue by johnatgit** [mogoweb/365browser#1]
我在输入框里输入任何网址，都不能打开网页。
启动过程中，浏览器一直弹出崩溃的提示框。。。

**Comment by JackyAndroid** [comment]
@johnatgit 可以参考https://github.com/Staray/ChromiumForAndroid项目升级下365 chromium版本

**Comment by JackyAndroid** [comment]
@johnatgit 可以参考 https://github.com/Staray/ChromiumForAndroid 项目升级下365 chromium版本

**Comment by mogoweb** [comment]
@johnatgit 能否提供一下相关信息？

**Comment by mogoweb** [comment]
please update the latest code.
